.github/workflows/python-package.yml
riptable/hypothesis_tests/test_categorical_property.py
riptable/hypothesis_tests/test_riptide_numpy_equivalency.py

Enable the tooling integration tests as well as the property based tests that use hypothesis.

TEST: Enable integration tests GH-10

---

.github/workflows/conda_package.yaml
.github/workflows/python-package.yml

Enable manual trigger of workflows and upload packages only when run manually.

Manual trigger of workflow and manual upload

---

riptable/rt_merge.py

Implement new 'merge_indices' function by refactoring rt.merge2 to split
out the logic from the beginning up to where the join is performed.
rt.merge2 now calls rt.merge_indices to do some validation + perform
the join itself, then it finishes up by producing the merged Dataset
as it did before.

Implement 'merge_indices' function. Fixes #30.

---

riptable/rt_merge.py
riptable/tests/test_merge.py

Fix bug #41 in rt.merge2() when performing an outer merge on multiple columns and the first column is a string-typed column.

Fix for multi-key outer merge2 bug with string cols (#41)

---

riptable/benchmarks/main.py
riptable/benchmarks/runner.py

Fixed an issue that caused the benchmark runner to crash and fail to save out results from benchmarks
that'd already completed earlier in the run; the crash was caused by parameterless benchmarks or
comparison functions not producing any Datasets, so we'd get an error when trying to call Dataset.hstack()
on an empty list.
Also added support for capturing versions of selected, relevant packages and saving them
as part of the benchmark metadata.

Fix crashing issue in benchmark runner caused by parameterless benchmarks

---

riptable/testing/array_assert.py
riptable/testing/randgen.py
riptable/tests/test_saveload.py

I implemented a unit test / repro case for #138 -- the bug also affects multi-column loads if all the columns loaded are missing from the same section(s) of the multi-section SDS file.

Repro/test for #138

---

riptable/testing/array_assert.py

Remove some temporary workarounds from the assert_categorical_equal() function
that were/are needed to handle issues with Categoricals created from FastArray-
derived array types like DateTimeNano. Instead of putting the workarounds in
the assertion logic, provide a flag to opt-out of category array type-checks
so individual tests have more flexible control over how strict the equality
checks are.

Remove some workarounds from assert_categorical_equal()

---

riptable/rt_struct.py

Modify ``Struct.__setattr__()`` to (mostly) avoid calling ``__getattr__()`` when replacing items.
This change makes it so ``Struct.__setattr__()`` avoids calling ``__getattr__()`` when an existing item in the ``Struct`` is being replaced; avoiding that call fixes a recursive case that can occur in derived classes overriding ``__setattr__()`` and ``__getattr__()``, eliminating the need for those classes to implement some complex workarounds for the issue.

Modify Struct.__setattr__() to (mostly) avoid a recursive edge case in derived classes

---

riptable/tests/test_saveload.py

This PR implements a reproduction (as a test case, currently marked with ``pytest.mark.xfail``) for #163. No functionality changes.

Repro for #163.

---

riptable/rt_merge.py

Move the logging calls in merge implementations to the ``logging.DEBUG`` level; many of the logging calls are for debugging/performance tracing purposes, and they're verbose enough they tend to clutter/dominate application logs at the INFO level. Make the logging calls a bit more structured-logging-friendly too.

Move merge logging to debug level.

---

riptable/__init__.py
riptable/rt_datetime.py
riptable/rt_matplotlib.py

Add the ability for matplotlib to plot Date, DateTimeNano, and TimeSpan objects.

Date time plotting

---

riptable/tests/test_dataset_slicing.py

Part of investigating issue #199

Add backwards step slicing test

---

riptable/rt_str.py
riptable/tests/test_str.py

Add support for array inputs to substr

Substr array

---

riptable/rt_categorical.py

fix docstring

---

riptable/benchmarks/bench_primops.py

Follow-up to #251 -- apply a similar pattern to numba-based benchmarking functions.

Control numba caching with global setting.

---

riptable/rt_categorical.py

Avoid exception upon missing attributes.

---

.github/workflows/python-package.yml
conda_recipe/meta.yaml

Update riptide_cpp to 1.7.4

---

conda_recipe/meta.yaml

Accounts for major.minor.patch version.

Set riptable_cpp min pin to x.x.x

---

riptable/rt_numpy.py
riptable/tests/test_ismember.py

Fixes rtosholdings/riptable/issues/254

Fix lossless ismember

---

riptable/rt_dataset.py
riptable/rt_fastarray.py
riptable/tests/test_dataset.py
riptable/tests/test_fastarray.py

This reverts commit fcbf8c0a8c331cd7fbc6d0f7467d4e4152990379, reversing
changes made to 2b73961d30a7226c4a8d4f34713a7fa418882a40.

Revert "Merge pull request #309 from rtosholdings/expose-op-methods"

---

conda_recipe/meta.yaml
riptable/rt_numpy.py
riptable/tests/test_groupbyops.py
riptable/tests/test_ismember.py
setup.py

* ismember issues with empty inputs and null values in assoc_copy
* Fix tests to catch MT groupby mean bug

v1.6.2-rc1

---

conda_recipe/meta.yaml
dev_tools/gen_requirements.py
docs/source/tutorial/tutorial_intro.ipynb
pyproject.toml
riptable/rt_categorical.py
riptable/rt_dataset.py
riptable/rt_fastarray.py
riptable/rt_groupby.py
riptable/rt_groupbynumba.py
riptable/rt_grouping.py
riptable/rt_io.py
riptable/rt_pdataset.py
riptable/tests/test_accum2.py
riptable/tests/test_base_function.py
riptable/tests/test_fastarray.py
riptable/tests/test_groupbyops.py
riptable/tests/test_merge.py
riptable/tests/test_saveload.py

* Significant speed up for grouped fill_forward, fill_backward
* Add toml to developer req
* Disable pydocstyle error 419
* Fix pytest xfail-strict configuration
* Zborowsk/add pytest cov
* Remove obsolete references

v1.6.3-rc1

---

docs/source/tutorial/tutorial_io.rst
docs/source/tutorial/tutorial_merge.rst
docs/source/tutorial/tutorial_missing_data.rst
docs/source/tutorial/tutorial_performance.rst
docs/source/tutorial/tutorial_sample_data.rst
riptable/rt_accumtable.py
riptable/rt_dataset.py
riptable/rt_fastarray.py
riptable/rt_groupbyops.py
riptable/rt_merge.py
riptable/rt_numpy.py
riptable/tests/test_accumtable.py
riptable/tests/test_categorical_groupby.py
riptable/tests/test_ismember.py
riptable/tests/test_merge.py

* add last_fancy and last_bool
* Use lossless common type for multikey ismember
* Docstring: Update Dataset.sample()
* Tutorial: Updates and fixes
* Docstring: fa.copy_invalid
* Allow suffixes as input to merge_lookup
* Docstring: rt_merge.merge_lookup()
* Fix accum cols
* Docstring: fa.doc
* Docstring: fa.inv
* Docstring: fa.differs
* Docstring: fa.fill_invalid
* Force named args in FA.isin

Latest v1.8.0
