rtosholdings/riptable

- .gitignore
The repository currently does not have a `.gitignore` file, which results in `git` attempting to track files and folders like `dist/` and `build/` when installing from source. This PR adds a standard python `.gitignore` file with an added ignore for emacs backup files (bc I'm an emacs person :-P).
> Creating a .gitignore

- .gitignore
- README.md
- docs/CONTRIBUTING.md
- environment.yml
This PR:
- adds an `environment.yml` file to setup the `rtdev` environment that is meant for developers to work in
- creates `CONTRIBUTING.md` and links to it from the `README.md`
This should be merged after #7, since I accidentally made that PR from my `master` branch, and the changes between #7 and this PR overlap. I will not do this in the future.
> Dev environment and contributing guide

- .github/workflows/conda_package.yaml
- conda_recipe/meta.yaml
It will fail to build until the `riptide_cpp` package is available from anaconda cloud.
> Up the riptde_cpp version to 1.6 and add conda_package.yaml workflow

- .github/workflows/conda_package.yaml
- conda_recipe/meta.yaml
- riptable/_version.py
- setup.py
FYI, the file `_version.py` will be written by setuptools_scm in build time when `python setup.py` runs.
Please make a up-to-date tag for the latest version (1.0.9). The current tag is only 1.0.3. The commits that changed `_version.py` look like good places to put the tags.
Thanks.
> Use setuptools_scm for versioning

- conda_recipe/bld.bat
Please see the comment in the code for the reason of doing this.
> Remove setuptools.pth file from the conda package on Windows

- docs/source/benchmarking.rst
Add a guide / tutorial on the internal (not ASV-based) benchmark suite in riptable to document how to run the benchmark suite and interpret the results.
> Add developer benchmarking guide.

- riptable/rt_categorical.py
I've added a couple of PEP 484 type annotations for the ``Categories`` class. These specific annotations are being added because they make a big difference in being able to infer the correct types for attributes/properties (and some return values of properties) within both ``Categories`` and ``Categorical``.
> Some PEP 484 type annotations for Categories

- riptable/rt_struct.py
This PR fixes an error in ``Struct._build_sds_meta_data()`` which occurs when a key in the ``Struct`` has type ``bytes`` vs. the usual (and expected?) ``str`` type. The longer-term solution might be to add a bit of logic to ``__setattr__`` and/or ``__setitem__`` for Struct to check for when they're given a ``bytes`` and normalize that to a ``str``; we'll need similar code in ``__getattr__`` and ``__getitem__`` to match too.
> Fix crash in Struct._build_sds_meta_data()

- docs/source/conf.py
The [current documentation](https://riptable.readthedocs.io/en/latest/py-modindex.html) is not ideal because all submodules of riptable are compiled onto a single page. As an example [here is the page for `rt_dataset`](https://riptable.readthedocs.io/en/latest/riptable.html#module-riptable.rt_dataset). For me, it takes a few seconds for the entire page to load and then navigate to the correct submodule.
This PR upgrades the docs by breaking the submodules onto different pages using the `sphinx-autoapi` package.
Specifically, this PR:
- adds some extensions to `conf.py` that are objectively useful (e.g. todo notes)
- adds an `autoapi` settings line at the end that points to the source directory
- commits the `docs/source/_static` directory that should have been committed from the start. …
> Documentation upgrade

- .github/workflows/python-package.yml
Migrate to the latest version of the ``setup-miniconda`` GH action. Prefer the conda-forge channel over the default channel in conda builds, as conda-forge is typically more up-to-date.
> Prefer conda-forge channel

- conda_recipe/meta.yaml
Users have reported riptable works as expected when interoperating with newer versions of pandas (e.g. 1.1.x, 1.2.x). It seems like we should be able to relax the upper-bound constraint. It'd be good to follow-up by adding a tox configuration to run the unit tests against several of the minor point-release versions of pandas to make sure the riptable <-> pandas interop code works across multiple versions of pandas, e.g. ``0.24``, ``1.0``, ``1.1``, ``1.2``.
This would address #121.
> Relax pandas version constraint upper-bound

- riptable/rt_numpy.py
- riptable/tests/test_categorical.py
- riptable/tests/test_rtnumpy.py
``rt.hstack()`` has a bug -- which is fixed by this PR -- where if called with instances of a derived array type (e.g. ``rt.Categorical``) defining it's own ``hstack()`` _classmethod_, and the derived array type's ``hstack()`` method raises an exception, ``rt.hstack()`` catches and suppresses the exception then falls back to the standard implementation. In addition to suppressing exceptions indicating bad/incompatible inputs (such as ``Categorical`` instances with different ``CategoryMode`` values), the standard implementation won't do any special handling (if/as needed) required by certain derived array types, so the returned array object will be broken/corrupted.
The change in this PR fixes the issue by checking for the presence of an ``hstack()`` method on the derived array class in a …
> Don't suppress errors in hstack() implementations for derived array types

- riptable/config.py
- riptable/rt_merge.py
- riptable/rt_str.py
A riptable user ran into a reproducible segfault in the numba-JIT-compiled
code for the fancy_index_fetch_keymap() function in merge, and was able to
definitively trace it back to numba's caching code. The issue is fairly rare
but since it's causing repeatable crashing for some users I'm disabling the
numba caching for riptable functions to provide a short-term (if not
long-term) fix.
This change also introduces a very simple settings/config class that could
be extended with additional configuration settings (to be controlled via
environment variables or some settings file); these would eventually be
used to populate _default_ values for various things like max number of
threads, which we normally auto-detect (and which the user can override),
but this'll allow users to override that …
> Disable numba caching due to related segfaults reported by users.

- riptable/rt_timezone.py
- riptable/testing/array_assert.py
- riptable/tests/test_datetime.py
Implemented equality-assertion functions for derived array types (in addition to the existing function for ``Categorical``). In particular, there's a function for asserting two ``DateTimeNano`` instances are equal incl. verifying the ``TimeZone`` objects for the arrays are equal.
> Testing functions

- riptable/Utils/rt_display_nested.py
- riptable/tests/test_struct.py
- fixes Struct.tree empty when any Struct is empty
- adds unit test for Struct.tree
> fix tree broken on empty Struct

- riptable/rt_fastarray.py
- riptable/rt_str.py
- riptable/tests/test_str.py
The recent changes to consolidate numba attributes to make all string functions
have both serial and parallel forms exposed a bug in numba 0.51.2 where the
parallelized version of the `FAString.nb_removetrailing` function caused an
internal compiler error in numba.
Also took the opportunity to re-organize the unit tests alphabetically (by the
name of the function being tested) to make it more obvious which functions have
tests and which don't. Implemented a unit test and test cases for `removetrailing`.
> Fix recently-introduced bug with parallel version of removetrailing.

- riptable/rt_sds.py
A user was running into an error when trying to load some data; I traced it back to the ``_multistack_categoricals()`` function in rt_sds.py making an assumption that the category arrays will always be non-empty for a ``Dictionary`` or ``IntEnum``-mode ``Categorical``.
The fix is to just check the dtype of one of the category arrays rather than extracting the first element and using ``isinstance()`` on it.
> Fix ``_multistack_categoricals()`` so it works even if there are no defined categories

- riptable/rt_sds.py
- riptable/tests/test_sds.py
This PR fixes the ``rt.sds_info()`` function so it's able to accept either a single path or a sequence/list of paths. This used to work but was broken when implementing support for ``pathlib`` in #68.
> Fix sds info multifile

- riptable/rt_grouping.py
Move printing of warning message behind a check for ``Grouping.DebugMode`` like similar messages elsewhere in the file.
> Fix for #161.

- riptable/testing/array_assert.py
In ``riptable.testing.array_assert.assert_categorical_equal``, check _only_ the types within the typecheck.
This fixes an issue where `check_cat_names=False` could be specified, but the function still checked the category names, causing incorrect assertion failures.
> Fix too-strict assertion check in ``assert_categorical_equal``.

- riptable/rt_datetime.py
This causes issues when attempting to plot a TimeSpanObject.
> Change TimeSpan __init__ to fall back to using long format by default.

- riptable/conftest.py
- riptable/rt_merge.py
Changes I made in #185 to address the logging verbosity from the ``rt_merge`` module also introduced bugs in some of the logging calls due to the way the ``extra=`` data was being passed in.
This PR fixes those changes and also adds a session-wide pytest fixture to help detect any broken logging calls going forward.
> Fix broken logging introduced in #185

- riptable/hypothesis_tests/test_riptide_numpy_equivalency.py
- riptable/rt_fastarray.py
- riptable/tests/test_fastarray_functions.py
Fall back to numpy to do the work.
Also fix hypythesis unit tests that were failing due to failure reason type mismatch.
Fixes #190
> Don't call rc.BooleanIndex() when dims mismatch

- riptable/rt_datetime.py
- riptable/rt_fastarray.py
- riptable/tests/test_datetime.py
- riptable/tests/test_fastarray.py
Per https://numpy.org/doc/stable/user/basics.subclassing.html, in order to handle post-view casting initialization.
Fixes #206
> Add array finalizer to date/time subclasses

- conda_recipe/meta.yaml
- environment.yml
- riptable/rt_categorical.py
- riptable/rt_dataset.py
- riptable/rt_datetime.py
- riptable/rt_fastarray.py
- riptable/rt_timezone.py
- riptable/tests/test_fastarray.py
- riptable/tests/test_interop_pyarrow.py
Implement the ``__arrow_array__()`` protocol for FastArray and some derived types to allow them to be converted properly to pyarrow arrays (e.g. to handle converting riptable invalid/NA values).
Implement ``from_arrow()`` staticmethods on FastArray and derived types. These can be used to convert directly to FastArray (or derived) instances, which in some cases will provide a performance boost by avoiding the need to pass data through pandas as an intermediate step (e.g. when loading data in certain formats, such as CSV).
Some cases of ``Categorical`` conversion (in either direction) still need to be implemented.
> Implement ``__arrow_array__()`` for FastArray and derived types.

- riptable/rt_dataset.py
- riptable/tests/test_dataset.py
Current logic relies on riptable's DST and timezone conversion but pandas `tz_localize` doesn't know how to handle nonexistent timestamp because of DST (for instance 1990/4/1 2AM Eastern time doesn't exist, which is the test). The new logic will convert to pandas using the UTC timestamp and then use pandas `tz_convert` to do the timezone conversion.
> Use pandas timezone conversion for to_pandas

- conda_recipe/meta.yaml
- riptable/tests/test_interop_pyarrow.py
The pyarrow interop test was constructing a masked array as a mix of nd.array and pyarrow.array, which is no longer valid in pyarrow v6.0. Passing both as nd.array fixes the test.
> Fix tests for pyarrow 6.0 break

- riptable/rt_groupbyops.py
Reduces chances of making a mistake by passing window as arg, or misspelling.
Fixes #245
> Make rolling_mean window required kwarg

- riptable/rt_numpy.py
- riptable/tests/test_ismember.py
This makes `assoc_index` work with `Datasets` and `pandas` object (without explicitly using checks for pandas types). It also opens the door for making some other existing functions more friendly to these inputs
> Ismember more general

- riptable/rt_fastarraynumba.py
- riptable/rt_groupbynumba.py
- riptable/rt_grouping.py
- riptable/rt_str.py
#144 missed some usages of numba and caching was enabled for most of these, leading to the same crashing behavior. This PR fixes the rest of the numba-decorated functions in the library so they respect the global setting controlling whether numba caching is enabled for functions (or not).
> Make all usages of numba respect the global setting controlling caching

- riptable/rt_dataset.py
- riptable/tests/test_dataset.py
Pass a list of dict values to underlying hstack() as required.
Fixes #260
> Fix Dataset.melt() for hstackable types

- riptable/rt_fastarray.py
- riptable/tests/test_interop_pyarrow.py
Converting null-terminated bytestring to stringarray uses length in dtype.
Converting first to bytearray then to stringarray works around this.
Fixes #249
> Work around pyarrow bytestring to stringarray bug

- riptable/rt_datetime.py
- riptable/tests/test_datetime.py
Avoids numeric overflow of DateScalar int32
Fixes #277
> Expand dtype to int64 before converting to seconds

- riptable/rt_fastarray.py
Must re-check support after attempted remediation.
Fixes #280
> Don't call rc.SetItem for unsupported cases

- conda_recipe/meta.yaml
Make the numpy dependency explicit rather than expecting it to be set up properly.
Ensures that we use the correct numpy version that's required by numba.
> Add numpy version to meta.yaml

- riptable/rt_categorical.py
If we need to add the categorical itself to the results of an apply() operation, add it with a unique name.
The previous implementation appears to have depended on the first entry in the names array to be None, so it would be defaulted to the unique name. Now that we use array_finalizer, arrays created from template may get the template array's name, and in this case would cause the result column being overwritten.
Fixes #285
> Use unique cat column name in apply() result

- conda_recipe/meta.yaml
Remove numpy from build section.
Retain it in run section, as that doesn't affect build hash.
> Remove numpy from build hash

- riptable/rt_grouping.py
- riptable/tests/test_grouping.py
Don't take the fast path if there are filtered entries in the index
Fixes #292
Fixes #170
Fixes #259
> Retain filtered index in Grouping.regroup()

- riptable/rt_categorical.py
- riptable/rt_datetime.py
- riptable/rt_fastarray.py
- riptable/tests/test_interop_pyarrow.py
Implement support for converting pyarrow.ChunkedArray to riptable array types. This is needed for converting from a pyarrow.Table -> riptable, because pyarrow.Table seems to always wrap it's arrays in a ChunkedArray.
> Support pyarrow.ChunkedArray -> riptable conversion

- riptable/rt_fastarray.py
I strongly suspect that there is a much cleaner way of doing this, I'm interpolating with zero prior python coding.
For the strawman example it does at least seem to do the right thing.
> Raise a TypeError if we try to do a stats reduce on non-arithmetic types

- .github/workflows/python-package.yml
- riptable/test_tooling_integration/ipykernel_integration_test.py
- riptable/test_tooling_integration/run.py
- riptable/tests/run.py
Improve the run scripts so they will propagate exit codes. This allows them to break the build if tests fail.
Disable the tooling integration tests since they actually fail, and will now fail the builds. This will need to be remedied (issue #313).
> Improve test run scripts
